# The name of the action
name: CI
# paths: will run tests only if code in the given directory changes

# When the action is triggered
on:
  push:
    branches:
      - master
    paths:
      - "*/*.py"
  pull_request:
    branches:
      - master
    paths:
      - "*/*.py"

# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    # Start mysql
    steps:
      - run: |
          sudo /etc/init.d/mysql start

      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Seed DB
      - name: Run seed DB scripts
        env:
          TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
          TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        run: |
          python db/seed/create_db.py

      # Move into the project folder and run pytest
      - name: Test with pytest
        working-directory: .
        run: pytest -vv